mybatis-plus:
  mapper-locations:
    - classpath:/mapper/**/*.xml
    #- classpath*:/mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.happy3ing.common.*.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
server:
  port: 80